# Оновлена версія файлу render.yaml для роботи з Playwright.

services:
  - type: web
    name: tableau-refresh-bot 
    env: python
    plan: free
    region: oregon 
    
    # ВАЖЛИВО: Оновлена команда збірки для встановлення Playwright та його браузерів
    # Ми використовуємо більш специфічну команду для встановлення лише Chromium.
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "gunicorn app:app"
      
    # Ваші змінні середовища
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: MY_API_KEY
        value: super-secret-12345
      - key: TABLEAU_USERNAME
        value: clir.tableau@gmail.com
      - key: TABLEAU_PASSWORD
        value: awes0MIUacc_24
      - key: TABLEAU_POST_URL
        value: https://public.tableau.com/profile/api/workbook/request_extract_refresh
      - key: TABLEAU_WORKBOOK_ID
        value: 49f38034-8408-4682-90f1-dbf6d81cbe59
